### ISSUE TITLE
TEA Phase 2 - Multiple Choice questions require STAAR formatting

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/cnx-recipes#286]
Copied from https://github.com/Connexions/oer.exports/issues/2766:

TEA style requires all multiple choice questions to be formatted in STAAR format. This means the answer choice letters need to be capitalized, bolded, and should not have a period after the letter.

The screenshot below is from Macroeconomics Ch. 1, however this applies to all TEA titles with multiple choice questions. Currently letter options are lower case, not bold, and have the period.

![bb607624-3bbb-11e7-9a13-6dca0da4f87b](https://user-images.githubusercontent.com/7863733/27922305-34158b04-6240-11e7-8269-0e3ebee6fbbc.png)

**Comment by helenemccarron** [comment]
The easier way to address this for TEA is to create proper styling via CSS and apply it via the stylesheet on the Gateway. 
A long term solution for a standard for OSX still needs to be considered.

**Comment by helenemccarron** [comment]
@chcase we are working on making sure the markup is consistent to ensure the STAAR requirements are met but the final result cannot be achieved without CSS. Could you please have your devs include the snippet below in the stylesheet for all books? Let me know if you have any questions.

```
.os-eoc [data-type="problem"] ol[data-number-style="lower-alpha"] {
  list-style-type: none;
}

.os-eoc [data-type="problem"] ol[data-number-style="lower-alpha"] > li {
  counter-increment: listAlphaCounter;
}
.os-eoc [data-type="problem"] ol[data-number-style="lower-alpha"] > li:before {
  content: counter(listAlphaCounter, upper-alpha) " ";
  font-weight: bold;
  float: left;
  width: 2em;
}
.os-eoc [data-type="problem"] ol[data-number-style="lower-alpha"]:first-child {
  counter-reset: listAlphaCounter;
}
```

**Comment by tomjw64** [comment]
@helenemccarron 

A similar solution, replacing `float: left` with `display: inline-block` and removing the space seemingly hidden by `width` as well as the `:first-child` selector:
```scss
.os-eoc [data-type="problem"] ol[data-number-style="lower-alpha"] {
  list-style-type: none;
  counter-reset: listAlphaCounter;
}
.os-eoc [data-type="problem"] ol[data-number-style="lower-alpha"] > li {
  counter-increment: listAlphaCounter;
}
.os-eoc [data-type="problem"] ol[data-number-style="lower-alpha"] > li:before {
  content: counter(listAlphaCounter, upper-alpha);
  font-weight: bold;
  display: inline-block;
  width: 2em;
}
```

**Comment by philschatz** [comment]
Now that https://github.com/Connexions/rhaptos.cnxmlutils/pull/159 is merged, the `data-number-style="..."` (but not the `data-bullet-style="..."`) attribute no longer exists. Now it is:

```
<ol type="1">...</ol>
<ol type="A">...</ol>
<ol type="a">...</ol>
<ol type="i">...</ol>
<ol type="I">...</ol>
```

to match https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol

Hmm, I wonder if there is a better way to represent this CSS.

See https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type and https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style for more info.

**Comment by helenemccarron** [comment]
@chcase Please use this version of the CSS 

```
.os-eoc [data-type="problem"] ol[type="a"] {
  list-style-type: none;
  counter-reset: listAlphaCounter;
}
.os-eoc [data-type="problem"] ol[type="a"] > li {
  counter-increment: listAlphaCounter;
}
.os-eoc [data-type="problem"] ol[type="a"] > li:before {
  content: counter(listAlphaCounter, upper-alpha);
  font-weight: bold;
  display: inline-block;
  width: 2em;
}
```

**Comment by tomjw64** [comment]
@philschatz from the source you gave, it looks like Firefox is unfortunately the only browser that supports `@counter-style`
![screenshot_10](https://user-images.githubusercontent.com/1285308/28941203-dff3c7ec-785c-11e7-8eb9-b42e1a67e75f.png)

**Comment by philschatz** [comment]
Confirmed at https://stg.texasgateway.org/resource/practice?book=261661#fs-idm39651536

![image](https://user-images.githubusercontent.com/253202/29427462-d92b0dca-8357-11e7-8a3b-c776fdfd88f3.png)

**Comment by openstaxalina** [comment]
@philschatz @Stackblocks Aren't the above questions, not answer choices?

The original description indicates the answer choices needed to have this treatment.

Apologies if I missed this info elsewhere - this is a very long issue!

**Comment by Stackblocks** [comment]
@openstaxalina Nope, you are correct. STAAR formatting is for multiple-choice answers. Nice save!

**Comment by openstaxalina** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7258102-249104445_1-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by Stackblocks** [comment]
![image](https://user-images.githubusercontent.com/12678235/29441227-5540ca30-838f-11e7-91fd-d81412cdefa0.png)
Confirmed that the questions choices are still lower case and followed by a `.` on WebView and the Gateway.

**Comment by openstaxalina** [comment]
Decision:
- Alan placing screenshot with correct styling in-book on the Gateway.
- Need to communicate w/ TEG that the rule needs to be extended to apply to Appendices (Helene, Phil and Alan confirming first).

**Comment by philschatz** [comment]
`@tomjw64` noticed that using the `display: flex` caused subscripts to render as superscripts and in sleuthing noticed that one option could be to change recipes to add an additional container `<div>` on list items. Instead, I tried hacking around to get CSS to "emulate" a list. Here's what I have with an example:

# Full Source

<details>

<summary>Click me for full Source Code that you can just open in a browser</summary>

```html
<html>
<head>
<style>

/* Note: use `:not(li> >` to allow nested lists to have the normal list styling) */
:not(li) > ol[type="a"] {
    list-style-type: none;
    counter-reset: fooCounter;
    /* Emulate the list padding/margins */
    padding: 0;
    padding-left: 1em;

    margin-left: 2em; /* use 2em instead of 1em so it is a little clearer that this is an answer choice. This matches the `left: -2em;` below */
    margin-top: 0;
    margin-bottom: 0;
}

:not(li) > ol[type="a"] > li {
    counter-increment: fooCounter;
}
:not(li) > ol[type="a"] > li::before {
    font-weight: bold;
    content: counter(fooCounter, upper-alpha);

    /* Move the character to the left of the list item but ensure it does not leave whitespace (because of `position: relative;`) */
    left: -2em; /* Use -2em instead of -1em so it is a little clearer that this is an answer choice */
    position: relative;
    width: 0;
    display: inline-block;
}

</style>
<body>
  <p>Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text </p>

<ol type="a">
<li>short</li>
<li>short</li>
<li>Subscripts and superscripts: foo<sub>subscript</sub> bar<sup>superscript</sup></li>
<li>Long text: ashf kjahsf kjasfkjaskfjaskjfha ksjfkdjhf kjsdhf ksjdhf kjsdhf kjsdhf ekjh akjsfh kjashf kjashf kjahsf kjasfkjaskfjaskjfha ksjfkdjhf kjsdhf ksjdhf kjsdhf kjsdhf ekjh akjsfh kjashf kjashf kjahsf kjasfkjaskfjaskjfha ksjfkdjhf kjsdhf ksjdhf kjsdhf kjsdhf ekjh akjsfh kjashf kjashf kjahsf kjasfkjaskfjaskjfha ksjfkdjhf kjsdhf ksjdhf kjsdhf kjsdhf ekjh akjsfh kjashf kjashf kjahsf kjasfkjaskfjaskjfha ksjfkdjhf kjsdhf ksjdhf kjsdhf kjsdhf ekjh akjsfh kjashf kjashf kjahsf kjasfkjaskfjaskjfha ksjfkdjhf kjsdhf ksjdhf kjsdhf kjsdhf </li>

<li class="-nested">Nested list:
  <ol type="a">
  <li>short</li>
  <li>short</li>
  <li>Subscripts and superscripts: foo<sub>subscript</sub> bar<sup>superscript</sup></li>
  <li>Long text: ashf kjahsf kjasfkjaskfjaskjfha ksjfkdjhf kjsdhf ksjdhf kjsdhf kjsdhf ekjh akjsfh kjashf kjashf kjahsf kjasfkjaskfjaskjfha ksjfkdjhf kjsdhf ksjdhf kjsdhf kjsdhf ekjh akjsfh kjashf kjashf kjahsf kjasfkjaskfjaskjfha ksjfkdjhf kjsdhf ksjdhf kjsdhf kjsdhf ekjh akjsfh kjashf kjashf kjahsf kjasfkjaskfjaskjfha ksjfkdjhf kjsdhf ksjdhf kjsdhf kjsdhf ekjh akjsfh kjashf kjashf kjahsf kjasfkjaskfjaskjfha ksjfkdjhf kjsdhf ksjdhf kjsdhf kjsdhf ekjh akjsfh kjashf kjashf kjahsf kjasfkjaskfjaskjfha ksjfkdjhf kjsdhf ksjdhf kjsdhf kjsdhf </li>
  <li>short</li>
  <li>With an image: <img src="https://cnx.org/images/logo.png" style="width: 200px;"/> and more text after</li>
  <li>With a figure: <figure><img src="https://cnx.org/images/logo.png" style="width: 200px;"/></figure> and more text after</li>
  <li>With a Table: <table><tr><td>[One table Cell]</td><td>[Another Table Cell]</td></tr><tr><td>[One table Cell]</td><td>[Another Table Cell]</td></tr></table> and more text after</li>
  </ol>

</li>
<li>short</li>
<li>With an image: <img src="https://cnx.org/images/logo.png" style="width: 200px;"/> and more text after</li>
<li>With a figure: <figure><img src="https://cnx.org/images/logo.png" style="width: 200px;"/></figure> and more text after</li>
<li>With a Table: <table><tr><td>[One table Cell]</td><td>[Another Table Cell]</td></tr><tr><td>[One table Cell]</td><td>[Another Table Cell]</td></tr></table> and more text after</li>
</ol>

<p>Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text Para text </p>
</body>
</html>
```

</details>


# CSS

```css
/* Note: use `:not(li> >` to allow nested lists to have the normal list styling) */
:not(li) > ol[type="a"] {
    list-style-type: none;
    counter-reset: fooCounter;
    /* Emulate the list padding/margins */
    padding: 0;
    padding-left: 1em;

    margin-left: 2em; /* use 2em instead of 1em so it is a little clearer that this is an answer choice. This matches the `left: -2em;` below */
    margin-top: 0;
    margin-bottom: 0;
}

:not(li) > ol[type="a"] > li {
    counter-increment: fooCounter;
}
:not(li) > ol[type="a"] > li::before {
    font-weight: bold;
    content: counter(fooCounter, upper-alpha);

    /* Move the character to the left of the list item but ensure it does not leave whitespace (because of `position: relative;`) */
    left: -2em; /* Use -2em instead of -1em so it is a little clearer that this is an answer choice */
    position: relative;
    width: 0;
    display: inline-block;
}
```

# Screenshot

![image](https://user-images.githubusercontent.com/253202/29580465-191fd43e-8744-11e7-8700-21daecb5df6a.png)
