### ISSUE TITLE
CSS changes to the Gateway

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-recipes#325]
Please make the following changes to the CSS in all the TEA books stylesheets.

Global change that makes the subscript look much better when not in Math - Apply only if desirable or limited to our books.

```css
sub {
    bottom: -0.50em;
}
```

Please add the following CSS
```css
.os-table .os-caption-container {
    font-size: 12px;
    padding: 0px;
    text-align: left;
}
.os-table, table.key-terms {
    display: table;
    width: 100%;
}
.os-table table {
    margin: .5em auto;
    width: 100%;
}
.os-table caption {
    color: #777;
    caption-side: bottom;
    text-align: left;
}
```

Modification to titles below is necessary to override
`.section-resource .resource-item .view-content span[data-type="title"]` applied elsewhere. No need to modify the general rule, this only for titles in tables.

```
 .os-table .os-title[data-type="title"] {
    font-size: 12px;
    color: #333;
    text-transform: none;
    display: inline;
    border-bottom: 0;
}
```

The following were originally found inside these selectors:
`  .page-dashboard-courses.page-dashboard-resources-step-two .center-wrapper .panel-col-last .inside #subcontent-container li.views-row .views-field.views-field-field-subcontent-html-body,
  .page-dashboard-binders.page-dashboard-resources-step-two .center-wrapper .panel-col-last .inside #subcontent-container li.views-row .views-field.views-field-field-subcontent-html-body
  .page-dashboard-resources.page-dashboard-resources-step-two .center-wrapper .panel-col-last .inside #subcontent-container li.views-row .views-field.views-field-field-subcontent-html-`

Please **delete** the following declarations. 

```css
/*
.os-eoc [data-type="problem"] ol[data-number-style="lower-alpha"] {
    list-style-type: none;
    counter-reset: listAlphaCounter;
}
.os-eoc [data-type="problem"] ol[data-number-style="lower-alpha"] > li {
    counter-increment: listAlphaCounter;
}
 .os-eoc [data-type="problem"] ol[data-number-style="lower-alpha"] > li:before {
    content: counter(listAlphaCounter, upper-alpha) " ";
    font-weight: bold;
    display: inline-block;
    margin-right: 1em;
}
*/
```

Please modify the declaration below to add the last line ` margin-left: 2em;`
This was originally found in the selector `.field-name-field-subcontent-html-body `

```
.os-eoc [data-type="problem"] ol[type="a"] {
    list-style-type: none;
    counter-reset: listAlphaCounter;
    /* add this line */ margin-left: 2em;
}
```

Please modify the declaration below to remove the last line ` display: flex;`
Add `display: block;` instead.
This was originally found in the selector `.field-name-field-subcontent-html-body `
```
 .os-eoc [data-type="problem"] ol[type="a"] > li {
    counter-increment: listAlphaCounter;
    display: block;
    display: flex; /*remove this line */
}
```

Please modify the declaration below to remove the line `margin-right: 1em;`
Add `display: block;` instead. Add those to declarations two the block:
```
    position: absolute;
    left: 4.5em;
```

This was originally found in the selector `.field-name-field-subcontent-html-body `

```
.os-eoc [data-type="problem"] ol[type="a"] > li:before {
    content: counter(listAlphaCounter, upper-alpha);
    font-weight: bold;
    display: inline-block;
    margin-right: 1em; /*delete this line*/
    position: absolute;
    left: 4.5em;
}
```

refs #286
